
class VM(object):
    """
    The meat of the interpreter, this class executes the AST
    """
    
    def __init__(self, ast):
        """
        
        Arguments:
        - `ast`: the ast generated by the parser
        """
        self._ast = ast
        
